grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True
    search_param_grid:
      fit_intercept:
      - True
      - False
  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: True
      alpha: 1.0
    search_param_grid:
      fit_intercept:
      - True
      - False
      alpha:
      - 0.
      - 0.1
      - 0.2
      - 1
      solver:
      - auto
      - svd
  module_2:
    class: Lasso
    module: sklearn.linear_model
    params:
      fit_intercept: True
      alpha: 1.0
      warm_start: True
      selection: random
    search_param_grid:
      alpha:
      - 0.05
      warm_start:
      - True
      - False
      selection:
      - random
  module_3:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      criterion: squared_error
      max_depth: 3
      min_samples_leaf: 2
      max_features: auto
    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      max_depth:
      - 4
      min_samples_leaf:
      - 3
      max_features:
      - auto
      - sqrt
  module_4:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 50
      n_jobs: -1
      criterion: squared_error
      max_depth: 3
      min_samples_leaf: 2
    search_param_grid:
      criterion:
      - friedman_mse
      max_depth:
      - 3
      - 4
      min_samples_leaf:
      - 3
      - 4
      oob_score:
      - True
      - False
      n_estimators:
      - 100
  module_5:
    class: AdaBoostRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
      loss: linear
      learning_rate: 1.0
    search_param_grid:
      n_estimators:
      - 150
      loss:
      - linear
      - square
      learning_rate:
      - 0.05
      - 0.1
  module_6:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
      loss: squared_error
      criterion: friedman_mse
    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      n_estimators:
      - 150
      loss:
      - absolute_error



